steps:
  # Build Image = docker build -t gcr.io/${PROJECT_ID}/node-image:latest
  - name: "gcr.io/cloud-builders/docker"
    id: "build-docker-image-from-dockerfile"
    args:
      - "build"
      - "-t"
      - "gcr.io/mycloudrunproject-348105/hello-cloudrun:$SHORT_SHA"
      - "."
  #Push image to GCR
  - name: "gcr.io/cloud-builders/docker"
    id: "push-docker-image-to-gcr"
    args:
      - "push"
      - "gcr.io/mycloudrunproject-348105/hello-cloudrun"
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloud-run"
    args:
      - "run"
      - "deploy"
      - "hello-cloudrun"
      - "--image"
      - "gcr.io/mycloudrunproject-348105/hello-cloudrun:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-northeast1"
      - "-allow"
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: hellocloudrun
